name: gdl_pytorch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - numpy
  - matplotlib
  - pytorch=2.4
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - torchinfo
  - lightning
  - torchmetrics